CREATE TABLE TB_ESTABLISHMENT (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE TB_USER (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE TB_DESCRIPTION_RAW_MATERIAL (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    DESCRIPTION VARCHAR(30) NOT NULL
);

CREATE TABLE TB_RAW_MATERIAL (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    ID_DESCRIPTION_RAW_MATERIAL CHAR(40) NOT NULL,
    ID_ESTABLISHMENT CHAR(40) NOT NULL
);

CREATE TABLE TB_HISTORICO_RAW_MATERIAL (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    DATE_DAY DATETIME NOT NULL,
    DATE_VALIDITY DATETIME,
    AMOUNT INT DEFAULT 0,
    UNIT_PRICE DECIMAL DEFAULT 0,
    ID_RAW_MATERIAL CHAR(40) NOT NULL
);

CREATE TABLE TB_SALE_DAY (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    DATE_DAY DATETIME NOT NULL,
    RESULT_DAY DECIMAL DEFAULT 0,
    ID_ESTABLISHMENT CHAR(40) NOT NULL
);

CREATE TABLE TB_ESTABLISHMENT_USER (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    ID_USER CHAR(40) NOT NULL,
    ID_ESTABLISHMENT CHAR(40) NOT NULL
);

-- DbSet

CREATE TABLE TB_STATISTICS_RAW_MATERIAL (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    DATE_DAY DATETIME NOT NULL,
    ESTIMATED_STOCK_DATE_EMPTY DATETIME,
    ID_RAW_MATERIAL CHAR(40) NOT NULL
);

CREATE TABLE TB_STATISTICS_DAY (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    DATE_DAY DATETIME NOT NULL,
    RAW_MATERIAL_EXPENDITURE DECIMAL DEFAULT 0,
    GROWTH_RATE INT DEFAULT 0,
    ID_ESTABLISHMENT CHAR(40) NOT NULL
);

CREATE TABLE TB_VALIDACAO_TESTE_DAY (
    ID CHAR(40) NOT NULL PRIMARY KEY,
    DATE_DAY DATETIME NOT NULL,
    IS_HOLIDAY BOOLEAN NOT NULL,
    GROWTH_RATE INT DEFAULT 0
);

-- FKs

ALTER TABLE TB_RAW_MATERIAL
ADD CONSTRAINT FK_ID_DESCRIPTION_RAW_MATERIAL
FOREIGN KEY (ID_DESCRIPTION_RAW_MATERIAL) REFERENCES TB_DESCRIPTION_RAW_MATERIAL(ID);

ALTER TABLE TB_RAW_MATERIAL
ADD CONSTRAINT FK_ID_ESTABLISHMENT
FOREIGN KEY (ID_ESTABLISHMENT) REFERENCES TB_ESTABLISHMENT(ID);

ALTER TABLE TB_HISTORICO_RAW_MATERIAL
ADD CONSTRAINT FK_ID_RAW_MATERIAL
FOREIGN KEY (ID_RAW_MATERIAL) REFERENCES TB_RAW_MATERIAL(ID);

ALTER TABLE TB_SALE_DAY
ADD CONSTRAINT FK_ID_ESTABLISHMENT
FOREIGN KEY (ID_ESTABLISHMENT) REFERENCES TB_ESTABLISHMENT(ID);

ALTER TABLE TB_STATISTICS_RAW_MATERIAL
ADD CONSTRAINT FK_ID_RAW_MATERIAL
FOREIGN KEY (ID_RAW_MATERIAL) REFERENCES TB_RAW_MATERIAL(ID);

ALTER TABLE TB_STATISTICS_DAY
ADD CONSTRAINT FK_ID_ESTABLISHMENT
FOREIGN KEY (ID_ESTABLISHMENT) REFERENCES TB_ESTABLISHMENT(ID);

ALTER TABLE TB_ESTABLISHMENT_USER
ADD CONSTRAINT FK_ID_USER
FOREIGN KEY (ID_USER) REFERENCES TB_USER(ID);

ALTER TABLE TB_ESTABLISHMENT_USER
ADD CONSTRAINT FK_ID_ESTABLISHMENT
FOREIGN KEY (ID_ESTABLISHMENT) REFERENCES TB_ESTABLISHMENT(ID);

- retirando establishmentUser pq não é um dado que 
vamos usar e tbm a relacao é 1:n e não n:m

- retirando a relacao 1:n já qu enão terá esse
controle no front, deixando ent 1:1 entre user e 
establishment