\connect stockSystemDB


/*CREATE DATABASE stockSystemDB;
CREATE TABLE OWNER (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL
);

CREATE TABLE ESTABLISHMENT (
    ID INT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    IDOWNER INT NOT NULL
);

CREATE TABLE DESCRIPTIONRAWMATERIAL (
    ID INT PRIMARY KEY,
    DESCRIPTION VARCHAR(30) NOT NULL
);

CREATE TABLE RAWMATERIAL (
    ID INT PRIMARY KEY,
    IDDESCRIPTIONRAWMATERIAL INT NOT NULL,
    IDESTABLISHMENT INT NOT NULL
);

CREATE TABLE HISTORICORAWMATERIAL (
    ID INT PRIMARY KEY,
    DATEDAY DATE NOT NULL,
    DATEVALIDITY DATE,
    AMOUNT INT DEFAULT 0,
    UNITPRICE DECIMAL DEFAULT 0,
    IDRAWMATERIAL INT NOT NULL
);

CREATE TABLE SALEDAY (
    ID INT PRIMARY KEY,
    DATEDAY DATE NOT NULL,
    RESULTDAY DECIMAL DEFAULT 0,
    IDESTABLISHMENT INT NOT NULL
);

CREATE TABLE STATISTICSRAWMATERIAL (
    ID INT PRIMARY KEY,
    DATEDAY DATE NOT NULL,
    ESTIMATEDSTOCKDATEEMPTY DATE,
    IDRAWMATERIAL INT NOT NULL
);

CREATE TABLE STATISTICSDAY (
    ID INT PRIMARY KEY,
    DATEDAY DATE NOT NULL,
    RAWMATERIALEXPENDITURE DECIMAL DEFAULT 0,
    GROWTHRATE INT DEFAULT 0,
    IDESTABLISHMENT INT NOT NULL
);

CREATE TABLE VALIDACAOTESTEDAY (
    ID INT PRIMARY KEY,
    DATEDAY DATE NOT NULL,
    ISHOLIDAY BOOLEAN NOT NULL,
    GROWTHRATE INT DEFAULT 0
);

ALTER TABLE RAWMATERIAL
ADD CONSTRAINT FK_IDDESCRIPTIONRAWMATERIAL
FOREIGN KEY (IDDESCRIPTIONRAWMATERIAL) REFERENCES DESCRIPTIONRAWMATERIAL(ID);

ALTER TABLE RAWMATERIAL
ADD CONSTRAINT FK_IDESTABLISHMENT
FOREIGN KEY (IDESTABLISHMENT) REFERENCES ESTABLISHMENT(ID);

ALTER TABLE HISTORICORAWMATERIAL
ADD CONSTRAINT FK_IDRAWMATERIAL
FOREIGN KEY (IDRAWMATERIAL) REFERENCES RAWMATERIAL(ID);

ALTER TABLE SALEDAY
ADD CONSTRAINT FK_IDESTABLISHMENT
FOREIGN KEY (IDESTABLISHMENT) REFERENCES ESTABLISHMENT(ID);

ALTER TABLE STATISTICSRAWMATERIAL
ADD CONSTRAINT FK_IDRAWMATERIAL
FOREIGN KEY (IDRAWMATERIAL) REFERENCES RAWMATERIAL(ID);

ALTER TABLE STATISTICSDAY
ADD CONSTRAINT FK_IDESTABLISHMENT
FOREIGN KEY (IDESTABLISHMENT) REFERENCES ESTABLISHMENT(ID);

ALTER TABLE ESTABLISHMENT
ADD CONSTRAINT FK_IDOWNER
FOREIGN KEY (IDOWNER) REFERENCES OWNER(ID);*/